# Generated by Django 4.2.5 on 2023-09-12 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(db_column='idGenero', primary_key=True, serialize=False)),
                ('tipoGenero', models.CharField(db_column='tipoGenero', max_length=100)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='fk_genero',
            field=models.ForeignKey(db_column='fk_genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.genero'),
        ),
    ]
