# Generated by Django 4.2.5 on 2023-10-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_supusuario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supusuario',
            name='idSupUsuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
