# Generated by Django 4.2.5 on 2023-10-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_supusuario_idsupusuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraUsuario',
            field=models.CharField(db_column='contra_Usuario', max_length=128),
        ),
    ]
