# Generated by Django 4.2.5 on 2023-10-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_avisosrecomendaciones_conocenumerosemergencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_ResPersona', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_cse', models.CharField(max_length=255)),
                ('opcion_cne', models.CharField(max_length=255)),
                ('opcion_uso911', models.CharField(max_length=255)),
                ('opcion_rapidez', models.CharField(max_length=255)),
                ('opcion_usarapp', models.CharField(max_length=255)),
                ('opcion_avisos', models.CharField(max_length=255)),
                ('opcion_mapa', models.CharField(max_length=255)),
                ('opcion_paleta', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='avisosrecomendaciones',
            old_name='id',
            new_name='id_AyR',
        ),
        migrations.RenameField(
            model_name='conocenumerosemergencia',
            old_name='id',
            new_name='id_CNEmergencia',
        ),
        migrations.RenameField(
            model_name='conoceserviciosemergencia',
            old_name='id',
            new_name='id_CSEmergencia',
        ),
        migrations.RenameField(
            model_name='mapainteractivo',
            old_name='id',
            new_name='id_MapaInteractivo',
        ),
        migrations.RenameField(
            model_name='paletacolores',
            old_name='id',
            new_name='id_PColores',
        ),
        migrations.RenameField(
            model_name='rapidezservicio',
            old_name='id',
            new_name='id_RServicio',
        ),
        migrations.RenameField(
            model_name='usarappemergencia',
            old_name='id',
            new_name='id_UApp',
        ),
        migrations.RenameField(
            model_name='uso911',
            old_name='id',
            new_name='id_Uso911',
        ),
    ]
