# Generated by Django 4.2.5 on 2023-10-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_formulario_rename_id_avisosrecomendaciones_id_ayr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='opcion_rapidez',
            field=models.IntegerField(),
        ),
    ]
